[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "libaoc2021"
path = "src/lib.rs"

[[bin]]
name = "aoc2021"
path = "src/main.rs"

[dependencies]
